### ISSUE TITLE
install error 

### ISSUE THREAD

**Issue by SaberLee112354** [MPI-Dortmund/cryolo#12]
When I refer to the link -- https://cryolo.readthedocs.io/en/stable/installation.html#install-cryolo to install cryolo with cuda 11, the command -- pip install 'cryolo[c11]' prompts the following error .

####################################################################################################

Building wheels for collected packages: cryolo
  Building wheel for cryolo (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [126 lines of output]
      /spshared/apps/miniconda3/envs/cryolo11/lib/python3.8/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
        warnings.warn(

/spshared/apps/miniconda3/envs/cryolo11/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      installing to build/bdist.linux-x86_64/wheel
      running install
      HTTP Error 403: Forbidden
      ############################################
      Unable to download initialization weights from https://ndownloader.figshare.com/files/16406843
      Try to download it manually from https://figshare.com/articles/Initialization_weights_for_crYOLO/8965541
      and save it to /spshared/apps/miniconda3/envs/cryolo11/lib/python3.8/site-packages/cryolo
      ############################################
      error: [Errno 2] No such file or directory: '/spshared/apps/miniconda3/envs/cryolo11/lib/python3.8/site-packages/cryolo/full_yolo_backend.h5'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for cryolo
  Running setup.py clean for cryolo
Failed to build cryolo
Installing collected packages: cryolo
  Running setup.py install for cryolo ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for cryolo did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      /spshared/apps/miniconda3/envs/cryolo11/lib/python3.8/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
        warnings.warn(
      running install
      /spshared/apps/miniconda3/envs/cryolo11/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      HTTP Error 403: Forbidden
      ############################################
      Unable to download initialization weights from https://ndownloader.figshare.com/files/16406843
      Try to download it manually from https://figshare.com/articles/Initialization_weights_for_crYOLO/8965541
      and save it to /spshared/apps/miniconda3/envs/cryolo11/lib/python3.8/site-packages/cryolo
      ############################################
      error: [Errno 2] No such file or directory: '/spshared/apps/miniconda3/envs/cryolo11/lib/python3.8/site-packages/cryolo/full_yolo_backend.h5'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> cryolo

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by thorstenwagner** [comment]
Hi!

Thanks for reporting this issue!

I tried to fix it. Can you try again:
```
pip install 'cryolo[c11]==1.9.2.b1' 
```

In case it works, I still recommend you to do what the error message says:

```
Try to download it manually from https://figshare.com/articles/Initialization_weights_for_crYOLO/8965541
and save it to /spshared/apps/miniconda3/envs/cryolo11/lib/python3.8/site-packages/cryolo
```

Let me know that works :-)

Best,
 Thorsten

**Comment by thorstenwagner** [comment]
I assume it work. Otherwise reopen.
