### ISSUE TITLE
Helical Segment Export to Relion

### ISSUE THREAD

**Issue by mpm116** [MPI-Dortmund/cryolo#16]
Hi,

I folllowed the documentation to export helical segments to relion4 by generating to autopick.star. I was unable to extract segments due to the error 'Prior information of helical segments is missing in (the star files generated by cryolo autopick).

These star files do contain _rlnAnglePsiPrior. I created a python script to add _rlnAngleTiltPrior to them but this did not solve the error. A work around has been using the start-end coordinates EMAN .box files generated  by cryolo to then segment and extract in RELION, however it would be nice to be able to use the cryolo segments, which may be more accurate with more curved aments...

Any ideas welcome?

Thanks
Max

**Comment by thorstenwagner** [comment]
Hi, 

thanks for reporting the issue. I think in our lab relion4 is not used so far for helical processing, so I can't comment on it but I will ask around.

What if you follow the instructions for relion3?
https://cryolo.readthedocs.io/en/stable/other/other.html#import-cryolo-filament-coordinates-into-relion

Is that not working anymore?

Best,
Thorsten

**Comment by thorstenwagner** [comment]
I close the issue, because there is no response.
