### ISSUE TITLE
Importing particle coordinates into Relion4

### ISSUE THREAD

**Issue by MXXXZ** [MPI-Dortmund/cryolo#17]
Hello, I have reconstructed tomograms using etomo, and I would like to extract particles from them for the subtomo process.
 After manually extracting particles using cryYOLO and obtaining .cbox and .coords files, how can I convert them into a format that can be used as input for reconstruction in relion4? The .star file generated by the priors2star command in the cryYOLO tutorial is different from what is required in relion4 (missing several necessary columns).
Are there any other operations required to import the coordination into the subtomo workflow?
As a beginner my problem description may not be accurate, hope you can understand.I would greatly appreciate it if you could reply to me!🤗

**Comment by thorstenwagner** [comment]
Hi,

sorry that it took me so long, I was in vacation:

Have you tried this? 
https://cryolo.readthedocs.io/en/stable/other/other.html#import-coordinates-into-relion-4

And it is **crYO**LO and cry ( :cry:  ) YOLO :-D

Best,
Thorsten

**Comment by MXXXZ** [comment]
I hope you had a pleasant vacation🏖️! Thank you for addressing my previous questions, though I haven't yet resolved my issues😵‍💫. I've listed them below in the hopes that you might have some time to provide answers:

In my situation, I intend to pick membrane protein particles on a spherical surface. 
1. When manually picking particles and training the model, should I choose the original unreconstructed images or the tomography-reconstructed images?
2. The .cbox file contains data columns (_CoordinateX, _CoordinateY, _CoordinateZ, _Width, _Height, _EstWidth, etc.). In the relion subtomo tutorial, the input coordinate file includes columns like _rlnCoordinateX, _rlnCoordinateY, _rlnCoordinateZ, _rlnOriginXAngst. I'm curious if the calculations for the box file and subtomo average are accomplished within relion, or if they require conversion using other software?

These processes are truly ingenious! I hope I can master them as well. I look forward to your response!🥺
Wishing you consistently good weather (though a bit of randomness might bring some delightful surprises).

Sincerely,
Mency

发件人: Thorsten Wagner
发送时间: 2023年7月31日 16:03
收件人: MPI-Dortmund/cryolo
抄送: MXXXZ; Manual
主题: Re: [MPI-Dortmund/cryolo] Importing particle coordinates into Relion4(Issue #17)

Hi,
sorry that it took me so long, I was in vacation:
Have you tried this?
https://cryolo.readthedocs.io/en/stable/other/other.html#import-coordinates-into-relion-4
And it is crYOLO and cry ( 😢 ) YOLO :-D
Best,
Thorsten

**Comment by thorstenwagner** [comment]
Regarding 1:
You should use the reconstructed tomogram

Regarding 2:
The cbox files can't be used directly in Relion. Here is how you get them into relion 4:
https://cryolo.readthedocs.io/en/stable/other/other.html#import-coordinates-into-relion-4

**Comment by MXXXZ** [comment]
Thank you very much for your response. I will continue to try! 
Best wishes!
