### ISSUE TITLE
problem with exporting coordinate files

### ISSUE THREAD

**Issue by NoorHV** [MPI-Dortmund/cryolo#18]
Hello!

It might be me, as I not experienced with this kind of data analysis, but I cannot export filaments as described in the tutorials in the documentation for picking filaments: When I press Save to dir in the organize_layer tab. I get the  following error: Shape of passed values is (X,4), indices imply (X,3), where x is, I presume, the number of points and I get this error no matter the number of slices I selected/picked or value of x.
Thank you in advance!
![Screenshot from 2023-08-01 12-35-22](https://github.com/MPI-Dortmund/cryolo/assets/141135797/167cc985-d757-48ad-a9f5-feaacc87939a)

**Comment by thorstenwagner** [comment]
Hi! Thanks for letting us know! This error should fixed in the latest napari boxmanager (0.4.4) version. Could you give it a try?

**Comment by thorstenwagner** [comment]
I assume it is fixed.
