### ISSUE TITLE
cryolo seems has problem in recognizing relion3.1 processed mrc files

### ISSUE THREAD

**Issue by ajian-he** [MPI-Dortmund/cryolo#3]
cryolo 1.74 has problem in recognizing relion3.1 processed mrc files (either motion corrected or ctf corrected), for relion3.0, looks ok

**Comment by thorstenwagner** [comment]
Hi Ajian,

thanks for letting me know!

Do you have an example micrograph for me?

Best,
Thorsten

**Comment by thorstenwagner** [comment]
Do you provide the training data as star file?

**Comment by thorstenwagner** [comment]
Please reopen it if the problem still exists
