### ISSUE TITLE
wxPython update

### ISSUE THREAD

**Issue by dorton21** [MPI-Dortmund/cryolo#5]
any chance we could get cryolo to support a newer version of wxPython? Installation of wxPython@4.0.4 has many errors if installed outside of conda. I would like to get cryolo packaged for Spack (https://spack.io/) so it could be better used on HPC servers. Restriction of wxPython to 4.0.4 causes many installation errors.

**Comment by thorstenwagner** [comment]
Hi,

which wxPython version would work better for you?

Best,
Thorsten

**Comment by dorton21** [comment]
Any chance I could get support for the latest version? wxpython@4.1.1.

**Comment by thorstenwagner** [comment]
Not for the lastest, but I made some tests and I think I can add it to the next release.

**Comment by dorton21** [comment]
Any updates on this?

**Comment by thorstenwagner** [comment]
I tried it and it works. But it requires several other libraries to be updated. Therefore I will do the upgrade with the next release. I hope this is fine?

Best
Thorsten 

15.07.2021 18:46:47 Desmond Orton ***@***.***>:

**Comment by dorton21** [comment]
Working it into the next release is fine. Just wanted to check in. Thank you for the help.

**Comment by dorton21** [comment]
Any ideas as to when the next release may be?

**Comment by thorstenwagner** [comment]
The lastest beta release is working working with wxpython 4.1.1:
https://cryolo.readthedocs.io/en/latest/installation.html#install-cryolo

Its quite stable I guess. We also use it internally already. Can't tell a date yet, when the new release will happen. Maybe I can tell you more next week.

**Comment by thorstenwagner** [comment]
I think we can close this. The wxpython in 1.8 beta works stable
