### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by jianhaoc** [MPI-Dortmund/cryolo#6]
Hi,
After I following below 3 command-lines, pip install doesn't work.
conda env remove --name cryolo
conda create -n cryolo -c conda-forge -c anaconda python=3.6 pyqt=5 cudnn=7.1.2 numpy==1.14.5 cython wxPython==4.0.4 intel-openmp==2019.4 pip=20.2.3
source activate cryolo

$ pip install 'cryolo[gpu]'
bash: pip: command not found...

So I activate cryolo with "conda activate cryolo", then run pip install 'cryolo[gpu]' again. But it looks like all packages have been installed (see below).

$ pip install 'cryolo[gpu]'
Requirement already satisfied: cryolo[gpu] in ./.local/lib/python3.6/site-packages (1.7.4)
Requirement already satisfied: mrcfile<=1.1.2,>=1.0.0 in ./.local/lib/python3.6/site-packages (from cryolo[gpu]) (1.1.2)
Requirement already satisfied: Cython in /opt/conda3/envs/cryolo/lib/python3.6/site-packages (from cryolo[gpu]) (0.29.23)
Requirement already satisfied: Keras==2.2.5 in ./.local/lib/python3.6/site-packages (from cryolo[gpu]) (2.2.5)
Requirement already satisfied: numpy==1.14.5 in /opt/conda3/envs/cryolo/lib/python3.6/site-packages (from cryolo[gpu]) (1.14.5)
Requirement already satisfied: h5py>=2.5.0 in ./.local/lib/python3.6/site-packages (from cryolo[gpu]) (2.10.0)
Requirement already satisfied: imageio>=2.3.0 in ./.local/lib/python3.6/site-packages (from cryolo[gpu]) (2.9.0)
Requirement already satisfied: Pillow>=6.0.0 in ./.local/lib/python3.6/site-packages (from cryolo[gpu]) (7.2.0)
Requirement already satisfied: tifffile==2019.7.2 in ./.local/lib/python3.6/site-packages (from cryolo[gpu]) (2019.7.2)
Requirement already satisfied: scipy>=1.3.0 in ./.local/lib/python3.6/site-packages (from cryolo[gpu]) (1.5.1)
Requirement already satisfied: terminaltables in ./.local/lib/python3.6/site-packages (from cryolo[gpu]) (3.1.0)
Requirement already satisfied: lineenhancer==1.0.8 in ./.local/lib/python3.6/site-packages (from cryolo[gpu]) (1.0.8)
Requirement already satisfied: cryoloBM>=1.3.6 in ./.local/lib/python3.6/site-packages (from cryolo[gpu]) (1.3.6)
Requirement already satisfied: ansi2html in ./.local/lib/python3.6/site-packages (from cryolo[gpu]) (1.5.2)
Requirement already satisfied: GooeyDev>=1.0.3.5 in ./.local/lib/python3.6/site-packages (from cryolo[gpu]) (1.0.3.5)
Requirement already satisfied: wxPython==4.0.4 in /opt/conda3/envs/cryolo/lib/python3.6/site-packages (from cryolo[gpu]) (4.0.4)
Requirement already satisfied: matplotlib==2.2.3 in ./.local/lib/python3.6/site-packages (from cryolo[gpu]) (2.2.3)
Requirement already satisfied: scikit-learn==0.22.2 in ./.local/lib/python3.6/site-packages (from cryolo[gpu]) (0.22.2)
Requirement already satisfied: watchdog in ./.local/lib/python3.6/site-packages (from cryolo[gpu]) (0.10.3)
Requirement already satisfied: tensorflow-gpu==1.10.1 in ./.local/lib/python3.6/site-packages (from cryolo[gpu]) (1.10.1)
Requirement already satisfied: janni[gpu]==0.1.4 in ./.local/lib/python3.6/site-packages (from cryolo[gpu]) (0.1.4)
Requirement already satisfied: six>=1.9.0 in /opt/conda3/envs/cryolo/lib/python3.6/site-packages (from Keras==2.2.5->cryolo[gpu]) (1.16.0)
Requirement already satisfied: keras-applications>=1.0.8 in ./.local/lib/python3.6/site-packages (from Keras==2.2.5->cryolo[gpu]) (1.0.8)
Requirement already satisfied: pyyaml in ./.local/lib/python3.6/site-packages (from Keras==2.2.5->cryolo[gpu]) (5.3.1)
Requirement already satisfied: keras-preprocessing>=1.1.0 in ./.local/lib/python3.6/site-packages (from Keras==2.2.5->cryolo[gpu]) (1.1.2)
Requirement already satisfied: colored>=1.3.93 in ./.local/lib/python3.6/site-packages (from GooeyDev>=1.0.3.5->cryolo[gpu]) (1.4.2)
Requirement already satisfied: psutil>=5.4.2 in ./.local/lib/python3.6/site-packages (from GooeyDev>=1.0.3.5->cryolo[gpu]) (5.7.2)
Requirement already satisfied: cycler>=0.10 in ./.local/lib/python3.6/site-packages (from matplotlib==2.2.3->cryolo[gpu]) (0.10.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in ./.local/lib/python3.6/site-packages (from matplotlib==2.2.3->cryolo[gpu]) (2.4.7)
Requirement already satisfied: pytz in ./.local/lib/python3.6/site-packages (from matplotlib==2.2.3->cryolo[gpu]) (2020.1)
Requirement already satisfied: kiwisolver>=1.0.1 in ./.local/lib/python3.6/site-packages (from matplotlib==2.2.3->cryolo[gpu]) (1.2.0)
Requirement already satisfied: python-dateutil>=2.1 in ./.local/lib/python3.6/site-packages (from matplotlib==2.2.3->cryolo[gpu]) (2.8.1)
Requirement already satisfied: joblib>=0.11 in ./.local/lib/python3.6/site-packages (from scikit-learn==0.22.2->cryolo[gpu]) (0.16.0)
Requirement already satisfied: pathtools>=0.1.1 in ./.local/lib/python3.6/site-packages (from watchdog->cryolo[gpu]) (0.1.2)
Requirement already satisfied: setuptools<=39.1.0 in ./.local/lib/python3.6/site-packages (from tensorflow-gpu==1.10.1->cryolo[gpu]) (39.1.0)
Requirement already satisfied: grpcio>=1.8.6 in ./.local/lib/python3.6/site-packages (from tensorflow-gpu==1.10.1->cryolo[gpu]) (1.30.0)
Requirement already satisfied: astor>=0.6.0 in ./.local/lib/python3.6/site-packages (from tensorflow-gpu==1.10.1->cryolo[gpu]) (0.8.1)
Requirement already satisfied: tensorboard<1.11.0,>=1.10.0 in ./.local/lib/python3.6/site-packages (from tensorflow-gpu==1.10.1->cryolo[gpu]) (1.10.0)
Requirement already satisfied: termcolor>=1.1.0 in ./.local/lib/python3.6/site-packages (from tensorflow-gpu==1.10.1->cryolo[gpu]) (1.1.0)
Requirement already satisfied: absl-py>=0.1.6 in ./.local/lib/python3.6/site-packages (from tensorflow-gpu==1.10.1->cryolo[gpu]) (0.9.0)
Requirement already satisfied: wheel>=0.26 in /opt/conda3/envs/cryolo/lib/python3.6/site-packages (from tensorflow-gpu==1.10.1->cryolo[gpu]) (0.36.2)
Requirement already satisfied: protobuf>=3.6.0 in ./.local/lib/python3.6/site-packages (from tensorflow-gpu==1.10.1->cryolo[gpu]) (3.12.2)
Requirement already satisfied: gast>=0.2.0 in ./.local/lib/python3.6/site-packages (from tensorflow-gpu==1.10.1->cryolo[gpu]) (0.3.3)
Requirement already satisfied: imagecodecs-lite==2019.2.22 in ./.local/lib/python3.6/site-packages (from janni[gpu]==0.1.4->cryolo[gpu]) (2019.2.22)
Requirement already satisfied: markdown>=2.6.8 in ./.local/lib/python3.6/site-packages (from tensorboard<1.11.0,>=1.10.0->tensorflow-gpu==1.10.1->cryolo[gpu]) (3.2.2)
Requirement already satisfied: werkzeug>=0.11.10 in ./.local/lib/python3.6/site-packages (from tensorboard<1.11.0,>=1.10.0->tensorflow-gpu==1.10.1->cryolo[gpu]) (1.0.1)
Requirement already satisfied: importlib-metadata; python_version < "3.8" in ./.local/lib/python3.6/site-packages (from markdown>=2.6.8->tensorboard<1.11.0,>=1.10.0->tensorflow-gpu==1.10.1->cryolo[gpu]) (1.7.0)
Requirement already satisfied: zipp>=0.5 in ./.local/lib/python3.6/site-packages (from importlib-metadata; python_version < "3.8"->markdown>=2.6.8->tensorboard<1.11.0,>=1.10.0->tensorflow-gpu==1.10.1->cryolo[gpu]) (3.1.0)

But I can't find cryolo_gui.py in /opt/conda3/envs/cryolo/bin/ or other places.
Did I miss anything during installation? Thank you!

Jianhao

**Comment by thorstenwagner** [comment]
Hi,

source activate cryolo is outdated. I need to update the documentation and replace it with conda activate cryolo

However, from your output it doesn't look like it used pip from your cryolo environment, beause it installed everything into

./.local/lib/python3.6/site-packages

So, can you please try to reinstall it but make sure that after you run conda activate cryolo that 

which pip 

gives you pip from your cryolo environment? 

Best
Thorsten 

04.07.2021 04:52:19 jianhaoc ***@***.***>:

**Comment by thorstenwagner** [comment]
I've updated the documentation. Now it is conda activate cryolo.

**Comment by thorstenwagner** [comment]
The just run the installation procedure on my local computer an everything worked fine. I hope it workes for you too now.

Thanks for finding the issue with source activate!

Best,
Thorsten

**Comment by jianhaoc** [comment]
Thank you! It works now.
